### ISSUE TITLE
Import and improve msgs from autoware_auto_msgs

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/autoware_msgs#2]
See https://github.com/autowarefoundation/autoware/discussions/99.
Related: https://gitlab.com/autowarefoundation/autoware.auto/autoware_auto_msgs/-/issues/28

@xmfcx edited:

I plan to keep this issue as an epic for the migration and configuration of the messages.

- [x] Control messages
  - [x] https://github.com/autowarefoundation/autoware_msgs/pull/11
- [ ] Geometry messages
- [ ] Mapping messages
  - [ ] https://github.com/autowarefoundation/autoware_msgs/pull/30
- [ ] Perception messages
- [ ] Planning messages
- [ ] Sensing messages
  - [x] https://github.com/autowarefoundation/autoware_msgs/pull/24
- [ ] System messages
- [ ] Vehicle messages

**Comment by xmfcx** [comment]
I plan to keep this issue as an epic for the migration and configuration of the messages.

- [x] Control messages
  - [x] https://github.com/autowarefoundation/autoware_msgs/pull/11
- [ ] Geometry messages
- [ ] Mapping messages
- [ ] Perception messages
- [ ] Planning messages
- [ ] Sensing messages
  - [x] https://github.com/autowarefoundation/autoware_msgs/pull/24
- [ ] System messages
- [ ] Vehicle messages

**Comment by kminoda** [comment]
@kenji-miyake Are there any reason why this is stopped? (no offence)
Is it just that we cannot afford enough human resources right now to do this task?

**Comment by kenji-miyake** [comment]
@kminoda I guess so. I only created this issue and is not working on it.
To move forward, TIER IV's component teams should propose their ideas.

**Comment by esteve** [comment]
@xmfcx @kenji-miyake is anyone working on this? I have to check with @mitsudome-r , but I'd be happy to help :slightly_smiling_face:

**Comment by kenji-miyake** [comment]
@esteve I believe it's slowly ongoing by each component team, but we need to organize the current situation for better efficiency in future work. I'll ask @xmfcx and @mitsudome-r.

**Comment by xmfcx** [comment]
Closing since autoware_auto_msgs is removed from Autoware.
