### ISSUE TITLE
Move route message

### ISSUE THREAD

**Issue by isamu-takagi** [autowarefoundation/autoware_msgs#34]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

I would like to move the `HADMapRoute` message to add [the route setting service](https://github.com/autowarefoundation/autoware_msgs/pull/33).  Also, I think it's hard to understand what the name `HADMapRoute` stands for. How about renaming it to `VectorMapRoute` or `LaneletRoute`?

### Purpose

Remove unnecessary dependencies when adding route setting service.

### Possible approaches

Move the following messages:

| Source | Destination |
| ----- | ----- |
| autoware_auto_planning_msgs/HADMapRoute.idl | autoware_planning_msgs/VectorMapRoute.msg |
| autoware_auto_mapping_msgs/HADMapSegment.idl | autoware_planning_msgs/VectorMapSegment.msg |
| autoware_auto_mapping_msgs/MapPrimitive.idl | autoware_planning_msgs/VectorMapPrimitive.msg |

### Definition of done

- [x] Add autoware_planning_msgs.
- [ ] Remove autoware_auto_planning_msgs.

**Comment by isamu-takagi** [comment]
I think HADMapSegment also needs to be changed. I heard that the reason it holds primitives, not just IDs, is that different types may use the same ID. The field `preferred_primitive_id` alone cannot identify a primitive, so it should be a primitive type.

**Comment by isamu-takagi** [comment]
Also, according to @mitsudome-r, segments and primitives are used by planning (not mapping), so I moved them.

**Comment by xmfcx** [comment]
We can perform moving of the `autoware_auto_planning_msgs` in another issue, so I'm closing this issue for now. If you think this is a mistake, feel free to reopen it.
